# Load this config by default
spring.application.name: nimbus-central
spring.profiles: default
# Server port to listen
server.port: 8761

# management property (temporary)
management.contextPath: /
spring.boot.admin.contextPath: /admin

# Cloud config
spring.cloud.config.server.git.uri: classpath:/config
spring.cloud.config.server.prefix: cloud
spring.profiles.active: native

#Eureka Specifics
eureka:
    environment: deployment
    datacenter: local
    server:
        eviction-interval-timer-in-ms: 5000
        # for single node only
        enableSelfPreservation: false
    client:
        registerWithEureka: false
        serviceUrl.defaultZone: http://${eureka.instance.hostname:localhost}:${server.port}/eureka/